name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # keep credentials so deploy action can push
          persist-credentials: true

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: .
          commit-message: "Deploy site via GitHub Actions"
          token: ${{ secrets.GITHUB_TOKEN }}
